#define PIN_AUDIO_RX GPIO_NUM_39
#define PIN_AUDIO_TX GPIO_NUM_38

#define PIN_BUTTON_LEFT GPIO_NUM_21
#define PIN_BUTTON_RIGHT GPIO_NUM_48
#define PIN_BUTTON_OK GPIO_NUM_47
#define PIN_BUTTON_TRIGGER GPIO_NUM_4

#define PIN_LED_IR GPIO_NUM_42
#define PIN_LED_BLUE GPIO_NUM_41
#define PIN_LED_AUX GPIO_NUM_40

#define PIN_IR_RX GPIO_NUM_6

#define SOUND_STARTUP 1 //TODO
#define SOUND_NO_MORE_SHOTS 2
#define SOUND_PEW 3

#define MESH_PREFIX "LasertagMesh"
#define MESH_PASSWORD "00000000"